@extends("layouts.app")
@section('content')
<div>
  <hero-section></hero-section>
  <top-categories></top-categories>
  <featured-products></featured-products>
  <app-banner></app-banner>
</div>
@endsection